# Generated by Django 4.2.7 on 2026-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_created_at_to_category_and_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='dismissed_comment_date',
            field=models.DateField(blank=True, help_text='Заметки до этой даты включительно не показываются на главном экране', null=True, verbose_name='Дата скрытой заметки'),
        ),
    ]
