# Generated by Django 4.2.7 on 2026-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_habit_dismissed_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersettings',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='last_sent_times',
            field=models.JSONField(blank=True, default=list, verbose_name='Отправленные времена за дату'),
        ),
    ]
